---
- hosts: test2-shinken
  remote_user: root

  tasks:
    - name : 1. groupe shinken
      group:
        name: shinken
        state: present

    - name : 2. utilisateur shinken
      user:
        name: shinken
        group: shinken
        state: present

    - name : 3. installation epel, pip et lsb
      yum:
        name: {{item}}
        state: present
      with_items:
        - epel-release
        - redhat-lsb
        - python-pip
    - name : 4. pip install de shinken
      pip:
        name: shinken
        state: present

