---
- hosts: test2-shinken
  remote_user: root

  tasks:
    - name : 1. groupe shinken
      group:
        name: shinken
        state: present

    - name : 2. utilisateur shinken
      user:
        name: shinken
        group: shinken
        state: present

    - name : 3. installation epel
      yum:
        name=epel-release
        state=present

    - name : 4. installation prérequis (pip et lsb entre autres)
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - redhat-lsb
        - python-pip
        - nagios-plugins
        - python-crypto
        - mongodb
        - mongodb-server
        - httpd-tools

    - name : 5. pip install
      pip:
        name: "{{item}}"
        state: present
      with_items:
        - cherrypy
        - shinken
        - bottle
        - pymongo
        - requests
        - arrow
        - passlib

    - name : 6. enable des services
      systemd:
        name: "{{item}}"
        state: started
        enabled: True
      with_items:
        - shinken
        - mongod

    - name: initialisation de shinken
      become: true
      become_user: shinken
      command: shinken --init
      args:
        creates: /home/shinken/.shinken.ini

    - name : 7. installation de la webui
      command: shinken install webui2

    - name: 8. Change broker-master configuration
      lineinfile:
        dest=/etc/shinken/brokers/broker-master.cfg
        state=present
        regexp='.*[^#] modules*'
        line="    modules webui2"

    - name: 9. restart shinken
      systemd:
        name: shinken
        state: restarted

    - name: 10. ouverture du port dans firewwall-cmd
      firewalld:
        permanent: true
        immediate: yes
        state: enabled
        port: 7767/tcp

