---
- hosts: test2-shinken
  remote_user: root

  tasks:
    - name : 1. groupe shinken
      group:
        name: shinken
        state: present

    - name : 2. utilisateur shinken
      user:
        name: shinken
        group: shinken
        state: present

    - name : 3. installation epel
      yum:
        name=epel-release
        state=present

    - name : 4. installation pip et lsb
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - redhat-lsb
        - python-pip
        - nagios-plugins
        - python-crypto
        - mongodb
        - mongodb-server
        - httpd-tools

    - name : 5. pip install
      pip:
        name: "{{item}}"
        state: present
      with_items:
        - cherrypy
        - shinken
