---
- name: 1. ajout des paquets les plus utiles
  apt:
    update_cache=yes
    state=latest
    name={{item}}
  with_items:
  - curl
  - tar
  - unzip 
  - wget
  - unzip
  - nano
  - tcpdump
  - elinks
  - whois
  - nmap
  - tree

- name: 2. ajout des alias 
  copy:
    src: bash.bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: 0644

