# sous-role  pour installer les dépendance de shinken

- name : 1. groupe shinken
  group:
    name: shinken
    state: present

- name : 2. utilisateur shinken
  user:
    name: shinken
    group: shinken
    state: present

- name : 3. installation epel
  yum:
    name: epel-release
    state: present

- name : 4. installation des dépendances
  yum:
    name={{item}}
    state=present
  with_items:
    - python-pycurl
    - python-setuptools
    - python-pymongo
    - mongodb
    - git



