- name: install shinken package
  yum:
    name: shinken
    state: present

- name:  chown var/*/shinken
  file:
    path: /var/{{item}}/shinken
    owner: shinken
    group: shinken
    recurse: yes
  with_items:
    - var
    - log
    - run

- name: activation des services
  systemd:
    state: started
    enabled: yes
    name: "{{item}}"
  with_items:
    - shinken
    - shinken-arbiter
    - shinken-broker
    - shinken-poller
    - shinken-reactionner
    - shinken-receiver
    - shinken-scheduler

- name: initialisation de shinken
  become: true
  become_user: shinken
  command: shinken --init
  args:
    creates: /home/shinken/.shinken.ini
