---
- hosts : test2-shinken
  
  tasks:
  - name : 1. installation des paquets de conforts
    yum: 
      name: "{{item}}"  
      state: latest
    with_items:
      - curl
      - nano
      - tar 
      - unzip
      - tcpdump
      - wget
      - elinks
      - whois
      - nmap
      - tree
      - net-tools


  - name : 2. ajout du fichier de conf d'alias
    copy:
      src: ../file/alias.sh
      dest: /etc/profile.d/alias.sh
      owner: root
      group: root
      mode: 0644

  - name : 3. ajout du dossier .ssh
    file: path=/home/evan/.ssh state=directory

  - name : 3. ajout de la clé publique pour l'utilisateur evan
    copy:
      src: ../file/authorized_keys
      dest: /home/evan/.ssh/authorized_keys
      owner: evan
      group: evan
      mode: 0644
