---
- name: 1. installation mariadb
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - mariadb-server
    - php-mysql
    - mariadb
    - MySQL-python

- name: 2. start mysql service
  service:
    name: mariadb
    state: started
    enabled: true

- name: 3. create database
  mysql_db:
    name: projet-web
    state: present

- name: 4. create a database user
  mysql_user:
    name: evan
    password: evan
    priv: "*.*:ALL"
    host: localhost
    state: present

